# environment.yaml

name: deploy_ml
channels:
  - conda-forge
dependencies:
  - python==3.8
  - numpy
  - pandas
  - scikit-learn
  - pytest
  - requests
  - fastapi==0.63.0
  - uvicorn
  - gunicorn
  - pip
  - pip:
    - flake8