name: Python CI/CD

on: 
  push:
    branches:
      - master

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
        
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        while read requirement; do conda install --yes $requirement || pip install $requirement; done < ./starter/requirements.txt

    - name: Lint with flake8
      run: |
        # stop the build if there are any flake8 throws errors
        $CONDA/bin/flake8 . --exclude=sanitycheck.py
     
    - name: Test with pytest
      run: |
        pytest -vv
        
  continuous-deployment:
    needs: continuous-integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Merge master -> production
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: production
          message: Merge master into production
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Render.com
      # Only run this step via deploywebhook, see https://docs.render.com/deploy-hooks
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
